added data to ui
archa-agrawal/todo-list-fe pull request #4
Opened 2022-05-31 22:14 UTC by archa-agrawal

2022-05-31 23:09 UTC, vnikhra requested changes

2022-05-31 23:09 UTC, vnikhra commented on todo-list-fe.js
> +   return document.getElementById('maintext').innerHTML = JSON.stringify(data)
Do we need to return anything from here

2022-05-31 23:09 UTC, vnikhra commented on todo-list-fe.js
> +    return loadList(todoData)
Do we need to return here

2022-06-01 00:36 UTC, archa-agrawal commented
![Screen Shot 2022-05-31 at 8 34 40 PM](https://user-images.githubusercontent.com/105752655/171305388-31261378-cb81-40ac-9f9e-8a68c3740392.png)

2022-06-01 00:47 UTC, vnikhra approved these changes

2022-06-01 00:50 UTC, merged